apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: polaris-db
  namespace: polaris
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2
  
  storage:
    storageClass: rook-ceph-block
    size: 5Gi
  
  bootstrap:
    initdb:
      database: polaris
      owner: polaris
  
  # Monitoring configuration
  monitoring:
    enablePodMonitor: true
